fix #3711 upgrade async-http-client
backport 16eff6ffb52ab78870b3ac0b46333c189de2db48

fix the following issue:
java.io.IOException: Resetting to invalid mark
with WS.url.post(InputStream)

(https://github.com/AsyncHttpClient/async-http-client/issues/760)

Conflicts:
	framework/project/Dependencies.scala
	framework/src/play-java-ws/src/test/scala/play/libs/ws/ning/NingWSSpec.scala