Convert .travis-jvmopts to .sbtopts
Without those, on my machine (both jdk8 and jdk11),
'sbt clean +publishLocal' would run out of memory throwing confusing errors
such as 'java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$'.
Apparently the JVM heuristics for selecting these values aren't very good yet,
and it would be helpful to supply some reasonable defaults as .sbtopts so new
contributors don't have to deal with this.

(cherry picked from commit 484b320f8ef07b8691449a1a4abe2c939b2fd782)