Work around SuchMethodError caused by the current for3Use2_13 approach
java.lang.NoSuchMethodError: 'akka.japi.function.Function akka.stream.Supervision$.resumingDecider()'
In case we ever use native Scala 3 artifacts in the 2.9 branch we can revert this commit