Explicitly depend on netty-transport-native-unix-common
Ref https://github.com/sbt/sbt/issues/4823

http://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.34.Final/netty-transport-native-epoll-4.1.34.Final.pom. Under Linux profile it says:

> The unix-common with classifier dependency is optional because it is not a runtime dependency, but a build time
> dependency to get the static library which is built directly into the shared library generated by this project.

and it makes netty-transport-native-unix-common an optional dependency, but Play directly uses `io.netty.channel.unix.UnixChannelOption`.
When using sbt 1.3.0-RC2 that uses Coursier, netty-transport-native-unix-common no longer becomes part of the resolution and it causes NoClassDefFoundError.

(cherry picked from commit 71f36ff2fbfc590cef5902d5126312a11fc5f3f2)